"""News-provider contract and centralized selection for fixture mode."""

from abc import ABC, abstractmethod
from datetime import datetime
import logging

from ..config import Settings, get_settings
from .schemas import NewsCandidateBatch


logger = logging.getLogger(__name__)


class NewsProviderError(RuntimeError):
    """Safe application-facing news-provider error."""


class NewsProvider(ABC):
    source: str
    is_live: bool

    @abstractmethod
    async def get_candidates(
        self, *, limit: int = 15, as_of: datetime | None = None
    ) -> NewsCandidateBatch: ...


def get_news_provider(settings: Settings | None = None) -> NewsProvider:
    """Return the deterministic provider; live search is owned by Market Agent."""

    selected = settings or get_settings()
    if selected.news_provider == "simulated":
        from .demo_provider import SimulatedNewsProvider

        logger.info("News provider selected: simulated")
        return SimulatedNewsProvider()
    raise NewsProviderError(
        "Google Search candidates are generated by market_intelligence_agent, "
        "not by a custom function provider. Set NEWS_PROVIDER=simulated for fixtures."
    )
